### ISSUE TITLE
Requires root in order to run?

### ISSUE THREAD

**Issue by audiomuze** [TechGeek01/BackDrop#12]
```
$ python backdrop.py
Traceback (most recent call last):
  File "/home/x/git/BackDrop/backdrop.py", line 2283, in <module>
    keyboard.is_pressed('alt')
  File "/home/x/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 410, in is_pressed
    _listener.start_if_necessary()
  File "/home/x/.local/lib/python3.10/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/home/x/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/home/x/.local/lib/python3.10/site-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/home/x/.local/lib/python3.10/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
    ensure_root()
  File "/home/x/.local/lib/python3.10/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.
```

**Comment by TechGeek01** [comment]
Yeah, that's related to the library used to capture keyboard shortcuts. I have not yet found a better solution to this, as Windows is my primary development platform.

A fix for this is in the works Soon™!

**Comment by TechGeek01** [comment]
Updated requirements.txt in commit bf49831
